### ISSUE TITLE
Проверка лабораторной работы № 2

### ISSUE THREAD

**Issue by MforMAD** [MforMAD/equation_solving#1]
Работу выполнил:
Лазарев Дмитрий Станиславович

To: @evgeny-p

**Comment by evgeny-p** [comment]
1. Неясен смысл дополнительного отступа в коммите https://github.com/MforMAD/equation_solving/commit/41f3edf234c33ea3299466d51285e92131c98377. Блок кода, как правило, пишется на одном уровне, за исключением меток и директив препроцессора, их форматирование может оговариваться отдельно.

1. Коммиты https://github.com/MforMAD/equation_solving/commit/9cae9576946b8a507ef3e7f774fead6b493def4a, https://github.com/MforMAD/equation_solving/commit/7f08cb2c6977868b1a1d30de57b900899ac32cbc и  https://github.com/MforMAD/equation_solving/commit/3a0862fe1b90785249495105513541cb9fe75d6a могли бы быть одним. За исключением строки с вычислением дискриминанта. При просмотре истории складывается впечатление, что каждый из них неполный. В первом не хватает контекста: почему именно 4 аргумента? Во втором появляется обработка аргумента, но возникает вопрос: где остальные?

1. В коммитах https://github.com/MforMAD/equation_solving/commit/7f08cb2c6977868b1a1d30de57b900899ac32cbc и https://github.com/MforMAD/equation_solving/commit/6dc85cd62b497f2b060de98dc4b2af1733eab658 присутствуют по два типа изменений: исправление ошибки/опечатки и функциональные изменения. Такие изменения лучше оформлять в отдельные коммиты. Это оказывается полезным при переписывании истории ветки: коммиты можно объединять, менять местами, редактировать и удалять. В процессе разработки история ветки может содержать множество мелких коммитов, которые перед мержем будут объединены. Таким образом, из истории изменений можно удалить шум, связанный с исправлением собственных ошибок. Для этих операций используются команды `git commit --amend` и `git rebase --interactive`. На занятиях этого не будет, остается на самостоятельное изучение.

1. Общепринятая практика: использовать императив в заголовках коммитов. См. [How to Write a Git Commit Message](http://chris.beams.io/posts/git-commit/#imperative). При написании заголовков коммитов на русском языке такой практики не встречал.

1. В конце заголовков точка не ставится (речь о заголовке текущей задачи).

Для сдачи работы достаточно исправить первый и последний пункты.

**Comment by MforMAD** [comment]
1. Исправил. Внешнее отображение в sublime text немного обмануло.
2. А как и где мне объяснить откуда, зачем и почему эти 4 аргумента? В комментариях в коде?

To: @evgeny-p

**Comment by evgeny-p** [comment]
> А как и где мне объяснить откуда, зачем и почему эти 4 аргумента? В комментариях в коде?

Если говорить об истории коммитов, то помещение разбора опций в один коммит в данном конкретном случае решило бы вопрос. Но при усложнении логики приложения ручной разбор опций порождает сложный в понимании и сопровождении код.

Недостаток комментариев в том, что они видны только разработчику, в то время, как информация об опциях приложения полезна еще и пользователям.

Для разбора аргументов командной строки существует ряд функций и библиотек. Самые простой вариант — функции [getopt и getopt_long](http://linux.die.net/man/3/getopt). Для C++ часто используют [boost::program_options](http://www.boost.org/doc/libs/1_60_0/doc/html/program_options/tutorial.html#idm45555218472112). Есть забавный пакет, портированный на множество языков — [docopt](http://docopt.org/). С ним, правда, связан ряд сложностей: функционал для С несколько ограничен, а для C++ требует относительно свежих версий компилятора.

Выбор и использование библиотек зависит от ситуации, принятых соглашений и иногда от личных предпочтений. В любом случае, приложение должно поддерживать опцию `--help` для вывода справки.

Для бо́льшей документируемости опции можно сделать именованными. Тогда запуск приложения мог бы выглядеть как:
```
./equation_solving -a 1 -b 2 -c 3
```

Работа принята. Задачу можно закрывать.
